<?php $collection = $this->getCollection(); ?>
<?php $helper = $this->getHelper(); ?>

<div id="cleversoft-shopby-product-list">
    <style> #infscr-loading { position: relative; text-align: center; margin: 0 auto; clear: both; }</style>
    <div id="top-description">
        <p>Normann Copenhagen is a Danish design company with the mission to create original and innovative products in a simple and contemporary design that withstands the test of time. Or in other words, to challenge conventional thinking and make the ordinary extraordinary through great design.</p>
    </div>
    <div id="zoo-product-listing" class="ajax-img-product-attribute wrapper grid products-grid products-grid-partitioned category-products-grid product_grid_style_4">
        <ol class="items product-items itemgrid itemgrid zoo-itemgrid-adaptive zoo-grid-4col trigger-equal-height">
            <?php foreach ($collection as $item){?>
                <?php $alternativePhoto = $helper->getImageUrl($item->getAlternativePhoto());?>
            <li class="product_hover product product-item product-instock">
                <div class="product-item-info  <?php if ($alternativePhoto){?>have-alternative-image<?php }?> " data-container="product-grid">
                    <div class="zoo-inner-product-item-info">
                        <div class="zoo-product-image">
                            <a href="<?php print $this->getUrl('*/*/page', ['id' => $item->getId()])?>" tabindex="-1" style="min-height: 200px"> <img class="product-image-photo clazyload" data-src="<?php print $helper->getImageUrl($item->getImageUrl());?>" src="<?php print $helper->getImageUrl($item->getPhoto());?>" alt="<?php print $item->getFullName(); ?>" style="display: block;">
                                <?php if ($alternativePhoto){?><span class="product-img-additional alt-image"><img class="img-responsive alt-img product-image-photo" src="<?php print $alternativePhoto;?>" alt="<?php print $item->getFullName(); ?>" width="auto" height="auto"></span><?php }?>
                            </a>
                        </div>
                        <div class="product details product-item-details">
                            <div class="hover-area product_shop_loop">
                                <h5 class="product-item-name"><a title="<?php print $item->getFullName(); ?>" href="<?php print $this->getUrl('*/*/page', ['id' => $item->getId()])?>" class="product-item-link"><?php print $item->getFullName(); ?></a></h5>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <?php } ?>
        </ol>
    </div>
</div>

